version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/ssdDrive/Media:/audiobooks
      - /mnt/ssdDrive/Media:/podcasts
      - /mnt/ssdDrive/Media:/config
      - /mnt/ssdDrive/Media:/metadata
