version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:develop
       container_name: jellyseerr
       environment:
            - BASE_URL=http://192.168.0.128:5055
            - LOG_LEVEL=debug
            - TZ=Australia/Sydney
       ports:
            - 5055:5055
       volumes:
            - /path/to/appdata/config:/app/config
       restart: unless-stopped
